name: 06 Build & Sign Docker Image

on:
  workflow_call:
    outputs:
      image-tag:
        value: ${{ jobs.docker.outputs.image-tag }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/o2m-frontend

jobs:
  docker:
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.image-ref.outputs.image }}

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch

      - name: Build and Push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./O2M-frontend
          file: ./O2M-frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

   
      - name: Define image reference
        id: image-ref
        run: |
          IMAGE="ghcr.io/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.image-ref.outputs.image }}
          format: cyclone-dx-json
          output-file: sbom.json

      - name: Sign image with Cosign
        run: cosign sign --yes ${{ steps.image-ref.outputs.image }}

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-o2m-frontend
          path: sbom.json
