name: 06 Build & Sign Docker Image

on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.docker.outputs.image }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: luisquirola04/pis_5to_dockerizado/o2m-frontend

jobs:
  docker:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.image.outputs.image }}

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./O2M-frontend
          file: ./O2M-frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Export image ref
        id: image
        run: |
          echo "image=ghcr.io/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

      - name: Pull image
        run: docker pull ${{ steps.image.outputs.image }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image-ref: ${{ steps.image.outputs.image }}
          format: cyclone-dx-json
          output-file: sbom.json

      - name: Sign image
        run: cosign sign --yes ${{ steps.image.outputs.image }}

      - uses: actions/upload-artifact@v4
        with:
          name: sbom-o2m-frontend
          path: sbom.json
